### ISSUE TITLE
Add Action API: DELETE /shopcarts/clear

### ISSUE THREAD

**Issue by alicelisisi** [NYU-Shopcarts/shopcarts#35]
**As a user** 
**I need a clear shopcarts functionality** 
**So that I don't have to remove items individually**

**Assumptions:** 
* There are items already added to the shopcart

**Acceptance Criteria:**

```
Given that `PUT /shopcarts/clear` is implemented
When the route is called
Then all items from the shopcart are removed
```

**Comment by kqg13** [comment]
@pranaypareek to ask on Slack about what is meant by _Action API_

**Comment by pranaypareek** [comment]
Just updated the original comment with the criteria.

Our route should be `PUT /shopcarts/clear` which removes all items from the collection that were added to shopcarts.

If there were no items, it should still return success.

**Comment by alicelisisi** [comment]
why do we use PUT instead of Delete? i thought we use DELETE when we want to remove things.

**Comment by pranaypareek** [comment]
@alicelisisi DELETE is used to delete a single resource eg. `DELETE /shopcarts/items/:id` will delete one single item.

But clearing up an entire collection involves multiple resources. There are two ways to do it:

* Keep track of all the items which are in the collection, and send out `DELETE /shopcarts/items/:id` for **each** one of them
* OR, have a single route which on the backend removes all the required items in one shot `PUT /shopcarts/items/clear`

This is why it'll be better to use a PUT or a POST.

**Comment by alicelisisi** [comment]
![screen shot 2018-04-17 at 1 32 53 am](https://user-images.githubusercontent.com/20344798/38825477-4cba5890-41df-11e8-8dac-410157906924.png)
![screen shot 2018-04-17 at 1 32 44 am](https://user-images.githubusercontent.com/20344798/38825481-4fd97448-41df-11e8-80d6-3c553c97486f.png)
In professor's example, it did not use PUT, It used Delete in both cases.

**Comment by pranaypareek** [comment]
Okay. I think I'd like to ask Prof @rofrano for the reasoning behind using DELETE in routes where we do not specify a specific and single resource to delete.

Before I explain further, I think it might be okay to use DELETE here (because that's what been told in the example) and we know that all we are doing is removing all the resources. So I can update the issue and we are good.

But if I had to start a conversation around it: If this was going to be anything close to production ready, I'd still stand with PUT or POST. The main reason being that deleting an entire set of resources might entail a workflow (or a set of functions being called instead of just removing all resources from the collection)

Let's say you delete items in the shopcarts, then it is possible that you might have to delete or update other resources which are dependent on the items in the shopcarts. eg. we might want to add the items back to the wishlist or you might want to call your recommendations API with the updated info that the user decided not to buy certain items.

All of this will only make sense when we are using a `PUT /shopcarts/items/clear`. It won't make sense to have a DELETE where we promise to only delete the resources but end up doing other things as well.

**Comment by pranaypareek** [comment]
Changing the verb from PUT to DELETE
